
CREATE TABLE IF NOT EXISTS courts (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    government VARCHAR(50) NOT NULL,
    address VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL
);